### ISSUE TITLE
Implement in-browser SQL

### ISSUE THREAD

**Issue by JoeGermuska** [NUKnightLab/sql-mysteries#1]
The [Select Star SQL](https://selectstarsql.com/) site demonstrates a method for hosting a SQLite server in a web page and offering web components which are SQL consoles.

Might be cool to use those to make the SQL mysteries work without installation.

**Comment by simonw** [comment]
I deployed a copy of the database using [Datasette](https://github.com/simonw/datasette) here - which means there's now a web interface you can use to query it here:

https://sql-murder-mystery.datasette.io/sql-murder-mystery

Let me know if this isn't OK and I can take it down again.

The command I used to deploy it is this one - but unfortunately the Zeit Now v1 platform I'm using here isn't accepting new signups for their older Docker style hosting:

```
$ datasette publish now sql-murder-mystery.db \
  --title="SQL Murder Mystery" \
  --about_url="https://github.com/NUKnightLab/sql-mysteries" \
  --about="NUKnightLab/sql-mysteries" \
  --alias sql-murder-mystery.datasette.io
```

**Comment by simonw** [comment]
Example query: https://sql-murder-mystery.datasette.io/sql-murder-mystery?sql=select+*+from+crime_scene_report+where+type+%3D+%27murder%27+and+city+%3D+%27SQL+City%27

**Comment by JoeGermuska** [comment]
that's awesome! thank you!

**Comment by PaHorton** [comment]
This is really awesome! Unfortunately it seems like you can't check the murderer using: 
```
INSERT INTO solution VALUES (1, "Insert Murderer Name Here");

SELECT value FROM solution;
```
It appears that Datasette only allows `SELECT`

**Comment by Joseph94m** [comment]
> This is really awesome! Unfortunately it seems like you can't check the murderer using:
> 
> ```
> INSERT INTO solution VALUES (1, "Insert Murderer Name Here");
> 
> SELECT value FROM solution;
> ```
> 
> It appears that Datasette only allows `SELECT`

I am facing the same issue. I have to know if i guessed that right!

**Comment by JoeGermuska** [comment]
It turns out the in-browser SQLite engine that _Select Star SQL_ uses supports inserts, is permissively licensed, and is pretty easy to implement.  I think we can have at least the "experienced" version up in a few days, and the full walkthrough won't take a lot longer.

**Comment by JoeGermuska** [comment]
And it's done! Check out http://mystery.knightlab.com/
