### ISSUE TITLE
Solution is too easy to infer

### ISSUE THREAD

**Issue by kiicia** [NUKnightLab/sql-mysteries#13]
First query is too revealing, just leave "SELECT * FROM sqlite_master", you can see trigger with response clearly hex-ed, just search for "online hex to ascii" and here it is.

Using hash would be a bit better, but still not ideal for limited range of possible inputs.

**Comment by JoeGermuska** [comment]
We do use a hash, since #2. Honestly, we're not trying to bullet-proof the thing. It's a game for learning, so we just wanted to protect people from accidentally spoiling the puzzle. 

But, y'know, we'll consider pull-requests, or even specific suggestions.

**Comment by kiicia** [comment]
Hash is one way function, you don’t use one way function thus you do not use hashing. I’ll think about something more specific.

**Comment by JoeGermuska** [comment]
Please forgive my imprecision. The point being that we didn't want to accidentally reveal the answer to people who were still trying to find it through the intended means.

Frankly, I would be delighted to have people figure out how to hack the solution, that's another great learning experience.
