### ISSUE TITLE
Mysql database file

### ISSUE THREAD

**Issue by dachev** [NUKnightLab/sql-mysteries#16]
It would be nice to have a database file that could be directly imported into MySQL/MariaDB

**Comment by JoeGermuska** [comment]
are people who are not yet ready to deal with importing the data into MySQL, so we are not motivated to provide exports.

That said, the database file is [available in this Git repo](https://github.com/NUKnightLab/sql-mysteries/blob/master/sql-murder-mystery.db) and there are guides on the internet for migrating SQLite to MySQL/Maria for those who are so motivated.
