### ISSUE TITLE
Checking the schema spoils the answer

### ISSUE THREAD

**Issue by maugier** [NUKnightLab/sql-mysteries#2]
Issuing `.schema` from the sqlite prompt immediately spoils the answer by showing the trigger logic.

SQLite does not seem to have a portable hash function, but the answer could at least be obfuscated against accidental viewing using `hex()`; i.e. change the trigger condition to

    CASE WHEN hex(new.value) = '4A657....

**Comment by JoeGermuska** [comment]
I just noticed that yesterday, and went down the hash rabbit hole.  I hadn't found a built-in alternative, but the hex function is a good idea. thanks!
