### ISSUE TITLE
Convert PDF to Markdown or LaTeX

### ISSUE THREAD

**Issue by henryx** [NUKnightLab/sql-mysteries#3]
In order to extend, modify or translate the game, it would be nice to convert PDF prompts to Markdown or LaTeX format, to simplify the management

**Comment by JoeGermuska** [comment]
Agreed. I'm most of the way through #1 , in which I'm adapting the PDFs to HTML, and I'm wishing they were in another form as well.  Accepting this as a good issue to fix.

**Comment by JoeGermuska** [comment]
Now that mystery.knightlab.com exists, I think we'll close this.  We don't have internal resources for translations, and the database itself really would need to be translated, not just the prompts (see #4) which makes that unfortunately too big a task -- although we welcome people who are so motivated to adapt this to work for other languages.
