### ISSUE TITLE
Alice in Wonderland Easter Egg?

### ISSUE THREAD

**Issue by mydatacz** [NUKnightLab/sql-mysteries#30]
Has anyone figured out a way to filter/sort the interview table to get the Alice in Wonderland Chapters/text in order to read it to make sense.  Wondering if this was just random text, or if there actually is a way to query, before I figuratively and literally try to go down that rabbit hole, lol. No spoilers please if so.

**Comment by JoeGermuska** [comment]
I hope it's not too much of a spoiler to say that I'm pretty sure that @Joonpark13 just used text from Project Gutenberg to create noise in the database. I'm fairly certain that there isn't an easter egg, although he didn't leave us with the code actually used to generate the database, so I could be wrong!

**Comment by mydatacz** [comment]
Thank you @JoeGermuska for your response.  My first thought was that it was random, but then I wondered.  I'll hold off unless @Joonpark13 tells me otherwise!

**Comment by Joonpark13** [comment]
No easter egg, sorry!

... Or is there? (just kidding, there isn't. final answer.)
