### ISSUE TITLE
Can't check answer with web-based version?

### ISSUE THREAD

**Issue by psfales** [NUKnightLab/sql-mysteries#6]
I tried to solve the mystery using the web-based system mentioned in the README.md file.  I solved the mystery, but (unless I am missing something) the web system only allows SELECT queries, so there is no way to do an INSERT to check your answer.   If that's correct, it might be worth mentioning in README file

**Comment by JoeGermuska** [comment]
ah...  You missed the part about the *new* web-based system, at mystery.knightlab.com -- which does support inserts.

And I forgot to remove the part about the Datasette-based web version, which doesn't support inserts, from the README.
